version: '3'
networks:
  network1:
    name: network1

services:
  nginx:
    container_name: nginx1
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/usr/share/nginx/html
    networks:
      - network1

  php1:
    container_name: php1
    build: ./
    volumes:
      - ./nginx:/usr/share/nginx/html
    networks:
      - network1
    depends_on:
      - mysql1

  mysql1:
    container_name: mysql1
    image: mysql 
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network1

  phpmyadmin1:
    container_name: phpmyadmin1
    image: phpmyadmin
    ports:
      - "1500:80"
    environment:
      - PMA_HOST=mysql1
    networks: 
      - network1
    depends_on:
      - mysql1
