version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mounting default.conf here
      - ./web:/var/www/html  # Application files
    ports:
      - "80:80"
    depends_on:
      - php-fpm
  php-fpm:
    image: php:8.3-fpm
    volumes:
      - ./web:/var/www/html  # Application files
